version: "3"
services:
  sidecar.local.logging:
    build:
      context: .
      dockerfile: fluent.Dockerfile
    ports:
      - 24224:24224
  main.local.logging:
    build:
      context: .
      dockerfile: main.Dockerfile
    logging:
      driver: fluentd
    depends_on:
      - sidecar.local.logging
